#!/bin/bash

# Azox Network - Production Deployment Script
# Streamlined deployment for any Fedora/RHEL server

set -e

echo "🚀 Azox Network - Production Deployment"
echo "======================================="

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Configuration
WEB_DIR="/var/www/azox"
DB_NAME="azox_network"
DB_USER="azox_user"

print_info "Starting Azox Network deployment..."
echo ""

# Check if running as root or with sudo
if [[ $EUID -ne 0 ]]; then
    print_error "This script must be run as root or with sudo"
    exit 1
fi

print_info "Step 1: Installing system requirements..."

# Update system
dnf update -y > /dev/null 2>&1

# Install required packages
dnf install -y httpd mariadb-server mariadb php php-mysqlnd php-json php-mbstring php-xml > /dev/null 2>&1
print_status "System packages installed"

print_info "Step 2: Starting and enabling services..."

# Start and enable services
systemctl start httpd mariadb
systemctl enable httpd mariadb
print_status "Services started and enabled"

print_info "Step 3: Configuring firewall..."

# Configure firewall
firewall-cmd --permanent --add-service=http > /dev/null 2>&1
firewall-cmd --permanent --add-service=https > /dev/null 2>&1
firewall-cmd --reload > /dev/null 2>&1
print_status "Firewall configured"

print_info "Step 4: Setting up SELinux..."

# Configure SELinux
setsebool -P httpd_can_network_connect 1 > /dev/null 2>&1
setsebool -P httpd_can_network_connect_db 1 > /dev/null 2>&1
setsebool -P httpd_read_user_content 1 > /dev/null 2>&1
print_status "SELinux configured"

print_info "Step 5: Creating web directory..."

# Create web directory
mkdir -p "$WEB_DIR"
print_status "Web directory created: $WEB_DIR"

print_info "Step 6: Copying application files..."

# Copy files (assuming script is run from project directory)
if [[ -f "index.php" ]]; then
    cp -r . "$WEB_DIR/"
    
    # Remove deployment scripts from web directory
    rm -f "$WEB_DIR"/deploy*.sh
    rm -f "$WEB_DIR"/install-requirements.sh
    rm -f "$WEB_DIR"/fix-*.sh
    rm -f "$WEB_DIR"/*.md
    rm -f "$WEB_DIR"/Todo.md
    
    print_status "Application files copied"
else
    print_error "index.php not found. Please run this script from the project directory."
    exit 1
fi

print_info "Step 7: Setting file permissions..."

# Set correct ownership and permissions
chown -R apache:apache "$WEB_DIR"
chmod -R 755 "$WEB_DIR"
chmod -R 644 "$WEB_DIR"/*.php
chmod -R 644 "$WEB_DIR"/*/*.php
chmod -R 644 "$WEB_DIR"/*/*/*.php

# Fix directory permissions
find "$WEB_DIR" -type d -exec chmod 755 {} \;

# Set SELinux contexts
restorecon -R "$WEB_DIR" > /dev/null 2>&1

print_status "File permissions set correctly"

print_info "Step 8: Setting up database..."

# Check if MariaDB is running
if ! systemctl is-active --quiet mariadb; then
    print_warning "MariaDB is not running. Attempting to start..."
    systemctl start mariadb
    sleep 2
fi

# Generate random password for database user
DB_PASSWORD=$(openssl rand -base64 32)

# Setup database
mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" 2>/dev/null || true
mysql -e "CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';" 2>/dev/null || true
mysql -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';" 2>/dev/null || true
mysql -e "FLUSH PRIVILEGES;" 2>/dev/null || true

print_status "Database and user created"

# Import database schema
if [[ -f "$WEB_DIR/config/database_simple.sql" ]]; then
    mysql "$DB_NAME" < "$WEB_DIR/config/database_simple.sql"
    print_status "Database schema imported"
else
    print_warning "Database schema file not found. You may need to import it manually."
fi

print_info "Step 9: Configuring database connection..."

# Create production database config
cat > "$WEB_DIR/config/database.php" << EOF
<?php
/**
 * Production Database Configuration
 * Auto-generated by deployment script
 */

\$host = 'localhost';
\$dbname = '$DB_NAME';
\$username = '$DB_USER';
\$password = '$DB_PASSWORD';

try {
    \$pdo = new PDO("mysql:host=\$host;dbname=\$dbname;charset=utf8mb4", \$username, \$password, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ]);
} catch (PDOException \$e) {
    error_log("Database connection failed: " . \$e->getMessage());
    die("Database connection failed. Please check your configuration.");
}

// Database helper functions
function executeQuery(\$sql, \$params = []) {
    global \$pdo;
    \$stmt = \$pdo->prepare(\$sql);
    \$stmt->execute(\$params);
    return \$stmt;
}

function fetchRow(\$sql, \$params = []) {
    \$stmt = executeQuery(\$sql, \$params);
    return \$stmt->fetch();
}

function fetchAll(\$sql, \$params = []) {
    \$stmt = executeQuery(\$sql, \$params);
    return \$stmt->fetchAll();
}

function fetchCount(\$sql, \$params = []) {
    \$stmt = executeQuery(\$sql, \$params);
    return \$stmt->fetchColumn();
}

function insertAndGetId(\$sql, \$params = []) {
    global \$pdo;
    executeQuery(\$sql, \$params);
    return \$pdo->lastInsertId();
}

function logActivity(\$message, \$level = 'info') {
    \$logFile = __DIR__ . '/../logs/activity.log';
    \$logDir = dirname(\$logFile);
    
    if (!is_dir(\$logDir)) {
        mkdir(\$logDir, 0755, true);
    }
    
    \$timestamp = date('Y-m-d H:i:s');
    \$logEntry = "[\$timestamp] [\$level] \$message" . PHP_EOL;
    file_put_contents(\$logFile, \$logEntry, FILE_APPEND | LOCK_EX);
}

// Add missing sanitizeOutput function
function sanitizeOutput(\$string) {
    return htmlspecialchars(\$string, ENT_QUOTES, 'UTF-8');
}
?>
EOF

# Set secure permissions on config file
chmod 600 "$WEB_DIR/config/database.php"
chown apache:apache "$WEB_DIR/config/database.php"

print_status "Database configuration created"

print_info "Step 10: Creating logs directory..."

# Create logs directory
mkdir -p "$WEB_DIR/logs"
chown apache:apache "$WEB_DIR/logs"
chmod 755 "$WEB_DIR/logs"

print_status "Logs directory created"

print_info "Step 11: Final verification..."

# Test Apache configuration
if httpd -t > /dev/null 2>&1; then
    print_status "Apache configuration is valid"
else
    print_warning "Apache configuration may have issues"
fi

# Restart Apache to ensure everything is loaded
systemctl restart httpd

# Test database connection
if mysql -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" -e "SELECT 1;" > /dev/null 2>&1; then
    print_status "Database connection test successful"
else
    print_warning "Database connection test failed"
fi

# Test web server
if curl -s -o /dev/null -w "%{http_code}" http://localhost | grep -q "200\|302"; then
    print_status "Web server test successful"
else
    print_warning "Web server test failed"
fi

echo ""
echo "🎉 Deployment Complete!"
echo "======================"
echo ""
echo "Your Azox Network website has been deployed successfully!"
echo ""
echo "📍 Installation Details:"
echo "   Web Directory: $WEB_DIR"
echo "   Database: $DB_NAME"
echo "   Database User: $DB_USER"
echo ""
echo "🔐 Database Password (SAVE THIS!):"
echo "   $DB_PASSWORD"
echo ""
echo "🌐 Access your site:"
echo "   Local: http://localhost"
echo "   External: http://$(hostname -I | awk '{print $1}')"
echo ""
echo "📋 Next Steps:"
echo "1. Test your website in a browser"
echo "2. Create your first admin user via the registration page"
echo "3. Configure your domain name and SSL certificate"
echo "4. Set up regular backups"
echo ""
echo "📚 Documentation:"
echo "   - DEPLOYMENT.md for detailed deployment info"
echo "   - FEDORA-TROUBLESHOOTING.md for common issues"
echo ""
print_status "Deployment completed successfully! 🚀"