#!/bin/bash

# Azox Network - Production Database Fix Script
# Run this script to fix common database connection issues

set -e

echo "🔧 Azox Network - Production Database Fix"
echo "========================================="

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    print_error "This script must be run as root or with sudo"
    exit 1
fi

# Configuration
WEB_DIR="/var/www/azox"
DB_NAME="azox_network"
DB_USER="azox_user"

print_info "Step 1: Checking if web directory exists..."
if [[ ! -d "$WEB_DIR" ]]; then
    print_error "Web directory $WEB_DIR not found. Please run the deployment script first."
    exit 1
fi
print_status "Web directory found"

print_info "Step 2: Starting MariaDB service..."
systemctl start mariadb || {
    print_warning "Failed to start MariaDB. Attempting to fix..."
    
    # Try to fix common MariaDB issues
    systemctl stop mariadb || true
    sleep 2
    
    # Check if MariaDB is installed
    if ! command -v mysql &> /dev/null; then
        print_info "Installing MariaDB..."
        dnf install -y mariadb-server mariadb
    fi
    
    # Try to start again
    systemctl start mariadb
}

systemctl enable mariadb
print_status "MariaDB service started and enabled"

print_info "Step 3: Checking database configuration..."
DB_CONFIG="$WEB_DIR/config/database.php"

if [[ ! -f "$DB_CONFIG" ]]; then
    print_warning "Database config not found. Creating new configuration..."
    
    # Generate new password
    DB_PASSWORD=$(openssl rand -base64 32)
    
    # Create database and user
    mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" 2>/dev/null || true
    mysql -e "CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';" 2>/dev/null || true
    mysql -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';" 2>/dev/null || true
    mysql -e "FLUSH PRIVILEGES;" 2>/dev/null || true
    
    # Create production database config
    cat > "$DB_CONFIG" << EOF
<?php
/**
 * Production Database Configuration
 * Auto-generated by fix script
 */

\$host = 'localhost';
\$dbname = '$DB_NAME';
\$username = '$DB_USER';
\$password = '$DB_PASSWORD';

try {
    \$pdo = new PDO("mysql:host=\$host;dbname=\$dbname;charset=utf8mb4", \$username, \$password, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ]);
} catch (PDOException \$e) {
    error_log("Database connection failed: " . \$e->getMessage());
    die("Database connection failed. Please check your configuration.");
}

// Database helper functions
function executeQuery(\$sql, \$params = []) {
    global \$pdo;
    \$stmt = \$pdo->prepare(\$sql);
    \$stmt->execute(\$params);
    return \$stmt;
}

function fetchRow(\$sql, \$params = []) {
    \$stmt = executeQuery(\$sql, \$params);
    return \$stmt->fetch();
}

function fetchAll(\$sql, \$params = []) {
    \$stmt = executeQuery(\$sql, \$params);
    return \$stmt->fetchAll();
}

function fetchCount(\$sql, \$params = []) {
    \$stmt = executeQuery(\$sql, \$params);
    return \$stmt->fetchColumn();
}

function insertAndGetId(\$sql, \$params = []) {
    global \$pdo;
    executeQuery(\$sql, \$params);
    return \$pdo->lastInsertId();
}

function logActivity(\$message, \$level = 'info') {
    \$logFile = __DIR__ . '/../logs/activity.log';
    \$logDir = dirname(\$logFile);
    
    if (!is_dir(\$logDir)) {
        mkdir(\$logDir, 0755, true);
    }
    
    \$timestamp = date('Y-m-d H:i:s');
    \$logEntry = "[\$timestamp] [\$level] \$message" . PHP_EOL;
    file_put_contents(\$logFile, \$logEntry, FILE_APPEND | LOCK_EX);
}

function sanitizeOutput(\$string) {
    return htmlspecialchars(\$string, ENT_QUOTES, 'UTF-8');
}
?>
EOF
    
    print_status "New database configuration created"
    echo "Database Password: $DB_PASSWORD"
    echo "SAVE THIS PASSWORD!"
    
else
    print_status "Database configuration exists"
    
    # Extract existing credentials - try both formats
    DB_PASSWORD=$(grep "\$password = '" "$DB_CONFIG" | sed "s/.*'\(.*\)'.*/\1/" | head -1)
    
    if [[ -z "$DB_PASSWORD" ]]; then
        # Try development format
        DB_PASSWORD=$(grep "define('DB_PASS'" "$DB_CONFIG" | sed "s/.*'\(.*\)'.*/\1/" | head -1)
    fi
    
    if [[ -z "$DB_PASSWORD" ]]; then
        print_warning "Could not extract database password from existing config"
        print_info "This likely means you have a development config. Creating new production config..."
        
        # Generate new password and recreate config
        DB_PASSWORD=$(openssl rand -base64 32)
        
        # Create database and user
        mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" 2>/dev/null || true
        mysql -e "DROP USER IF EXISTS '$DB_USER'@'localhost';" 2>/dev/null || true
        mysql -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';" 2>/dev/null || true
        mysql -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';" 2>/dev/null || true
        mysql -e "FLUSH PRIVILEGES;" 2>/dev/null || true
        
        # Create new production config
        cat > "$DB_CONFIG" << EOF
<?php
/**
 * Production Database Configuration
 * Auto-generated by fix script
 */

\$host = 'localhost';
\$dbname = '$DB_NAME';
\$username = '$DB_USER';
\$password = '$DB_PASSWORD';

try {
    \$pdo = new PDO("mysql:host=\$host;dbname=\$dbname;charset=utf8mb4", \$username, \$password, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ]);
} catch (PDOException \$e) {
    error_log("Database connection failed: " . \$e->getMessage());
    die("Database connection failed. Please check your configuration.");
}

// Database helper functions
function executeQuery(\$sql, \$params = []) {
    global \$pdo;
    \$stmt = \$pdo->prepare(\$sql);
    \$stmt->execute(\$params);
    return \$stmt;
}

function fetchRow(\$sql, \$params = []) {
    \$stmt = executeQuery(\$sql, \$params);
    return \$stmt->fetch();
}

function fetchAll(\$sql, \$params = []) {
    \$stmt = executeQuery(\$sql, \$params);
    return \$stmt->fetchAll();
}

function fetchCount(\$sql, \$params = []) {
    \$stmt = executeQuery(\$sql, \$params);
    return \$stmt->fetchColumn();
}

function insertAndGetId(\$sql, \$params = []) {
    global \$pdo;
    executeQuery(\$sql, \$params);
    return \$pdo->lastInsertId();
}

function logActivity(\$message, \$level = 'info') {
    \$logFile = __DIR__ . '/../logs/activity.log';
    \$logDir = dirname(\$logFile);
    
    if (!is_dir(\$logDir)) {
        mkdir(\$logDir, 0755, true);
    }
    
    \$timestamp = date('Y-m-d H:i:s');
    \$logEntry = "[\$timestamp] [\$level] \$message" . PHP_EOL;
    file_put_contents(\$logFile, \$logEntry, FILE_APPEND | LOCK_EX);
}

function sanitizeOutput(\$string) {
    return htmlspecialchars(\$string, ENT_QUOTES, 'UTF-8');
}
?>
EOF
        
        print_status "New production database configuration created"
        echo "New Database Password: $DB_PASSWORD"
        echo "SAVE THIS PASSWORD!"
    fi
fi

print_info "Step 4: Testing database connection..."
if mysql -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" -e "SELECT 1;" > /dev/null 2>&1; then
    print_status "Database connection successful"
else
    print_warning "Database connection failed. Recreating database and user..."
    
    # Drop and recreate user with correct password
    mysql -e "DROP USER IF EXISTS '$DB_USER'@'localhost';" 2>/dev/null || true
    mysql -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';" 2>/dev/null || true
    mysql -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';" 2>/dev/null || true
    mysql -e "FLUSH PRIVILEGES;" 2>/dev/null || true
    
    # Test again
    if mysql -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" -e "SELECT 1;" > /dev/null 2>&1; then
        print_status "Database connection fixed"
    else
        print_error "Still cannot connect to database. Manual intervention required."
        exit 1
    fi
fi

print_info "Step 5: Importing database schema..."
if [[ -f "$WEB_DIR/config/database_simple.sql" ]]; then
    mysql -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" < "$WEB_DIR/config/database_simple.sql" 2>/dev/null || true
    print_status "Database schema imported"
else
    print_warning "Database schema file not found"
fi

print_info "Step 6: Setting correct file permissions..."
chown apache:apache "$DB_CONFIG"
chmod 600 "$DB_CONFIG"

# Create logs directory
mkdir -p "$WEB_DIR/logs"
chown apache:apache "$WEB_DIR/logs"
chmod 755 "$WEB_DIR/logs"

print_status "File permissions set"

print_info "Step 7: Restarting Apache..."
systemctl restart httpd
print_status "Apache restarted"

print_info "Step 8: Testing web server..."
if curl -s -o /dev/null -w "%{http_code}" http://localhost | grep -q "200\|302"; then
    print_status "Web server test successful"
else
    print_warning "Web server test failed - check Apache logs"
fi

echo ""
echo "🎉 Database Fix Complete!"
echo "========================"
echo ""
echo "Your database connection should now be working."
echo "Test your website at: http://$(hostname -I | awk '{print $1}')"
echo ""
echo "If you still see issues, run the diagnostic script:"
echo "php /var/www/azox/debug/diagnose-production.php"
echo ""