#!/bin/bash

# Azox Network - Simple Production Database Fix
# This script handles both development and production config formats

set -e

echo "🔧 Azox Network - Simple Database Fix"
echo "====================================="

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    print_error "This script must be run as root or with sudo"
    exit 1
fi

# Configuration
WEB_DIR="/var/www/azox"
DB_NAME="azox_network"
DB_USER="azox_user"
DB_PASSWORD=$(openssl rand -base64 32)

print_info "Step 1: Checking web directory..."
if [[ ! -d "$WEB_DIR" ]]; then
    print_error "Web directory $WEB_DIR not found. Please run deployment first."
    exit 1
fi
print_status "Web directory found"

print_info "Step 2: Starting MariaDB..."
systemctl start mariadb || {
    print_warning "MariaDB failed to start. Installing/fixing..."
    dnf install -y mariadb-server mariadb
    systemctl start mariadb
}
systemctl enable mariadb
print_status "MariaDB running"

print_info "Step 3: Setting up database..."
# Create database and user (drop existing to avoid conflicts)
mysql -e "DROP DATABASE IF EXISTS $DB_NAME;" 2>/dev/null || true
mysql -e "DROP USER IF EXISTS '$DB_USER'@'localhost';" 2>/dev/null || true
mysql -e "CREATE DATABASE $DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
mysql -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';"
mysql -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';"
mysql -e "FLUSH PRIVILEGES;"
print_status "Database and user created"

print_info "Step 4: Creating production config..."
# Always create a fresh production config
cat > "$WEB_DIR/config/database.php" << 'EOF'
<?php
/**
 * Production Database Configuration
 * Auto-generated by simple fix script
 */

$host = 'localhost';
$dbname = 'azox_network';
$username = 'azox_user';
$password = 'PLACEHOLDER_PASSWORD';

try {
    $pdo = new PDO("mysql:host=$host;dbname=$dbname;charset=utf8mb4", $username, $password, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ]);
} catch (PDOException $e) {
    error_log("Database connection failed: " . $e->getMessage());
    die("Database connection failed. Please check your configuration.");
}

function executeQuery($sql, $params = []) {
    global $pdo;
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    return $stmt;
}

function fetchRow($sql, $params = []) {
    $stmt = executeQuery($sql, $params);
    return $stmt->fetch();
}

function fetchAll($sql, $params = []) {
    $stmt = executeQuery($sql, $params);
    return $stmt->fetchAll();
}

function fetchCount($sql, $params = []) {
    $stmt = executeQuery($sql, $params);
    return $stmt->fetchColumn();
}

function insertAndGetId($sql, $params = []) {
    global $pdo;
    executeQuery($sql, $params);
    return $pdo->lastInsertId();
}

function logActivity($message, $level = 'info') {
    $logFile = __DIR__ . '/../logs/activity.log';
    $logDir = dirname($logFile);
    if (!is_dir($logDir)) {
        mkdir($logDir, 0755, true);
    }
    $timestamp = date('Y-m-d H:i:s');
    $logEntry = "[$timestamp] [$level] $message" . PHP_EOL;
    file_put_contents($logFile, $logEntry, FILE_APPEND | LOCK_EX);
}

function sanitizeOutput($string) {
    return htmlspecialchars($string, ENT_QUOTES, 'UTF-8');
}
?>
EOF

# Replace placeholder with actual password
sed -i "s/PLACEHOLDER_PASSWORD/$DB_PASSWORD/g" "$WEB_DIR/config/database.php"
print_status "Production config created"

print_info "Step 5: Importing database schema..."
if [[ -f "$WEB_DIR/config/database_simple.sql" ]]; then
    mysql -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" < "$WEB_DIR/config/database_simple.sql"
    print_status "Database schema imported"
elif [[ -f "$WEB_DIR/config/database.sql" ]]; then
    mysql -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" < "$WEB_DIR/config/database.sql"
    print_status "Database schema imported"
else
    print_warning "No database schema file found"
fi

print_info "Step 6: Setting permissions..."
chown apache:apache "$WEB_DIR/config/database.php"
chmod 600 "$WEB_DIR/config/database.php"
mkdir -p "$WEB_DIR/logs"
chown apache:apache "$WEB_DIR/logs"
chmod 755 "$WEB_DIR/logs"
print_status "Permissions set"

print_info "Step 7: Testing database connection..."
if mysql -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" -e "SELECT 1;" > /dev/null 2>&1; then
    print_status "Database connection successful"
else
    print_error "Database connection test failed"
    exit 1
fi

print_info "Step 8: Restarting Apache..."
systemctl restart httpd
print_status "Apache restarted"

print_info "Step 9: Testing website..."
sleep 2
if curl -s -o /dev/null -w "%{http_code}" http://localhost | grep -q "200"; then
    print_status "Website is responding"
else
    print_warning "Website test inconclusive - check manually"
fi

echo ""
echo "🎉 Fix Complete!"
echo "================"
echo ""
echo "✅ Database: $DB_NAME"
echo "✅ User: $DB_USER"
echo "🔐 Password: $DB_PASSWORD"
echo ""
echo "IMPORTANT: Save this password!"
echo ""
echo "Your website should now be working at:"
echo "http://$(hostname -I | awk '{print $1}')"
echo ""
echo "If you still have issues, check:"
echo "- Apache logs: sudo tail -f /var/log/httpd/error_log"
echo "- Run diagnostic: php $WEB_DIR/debug/diagnose-production.php"
echo ""